export enum ModuleNameEnum {
        Background = 38,
        Stakeholder = 39,
        Culture = 40,
        Negotionality = 41,
        ThisNegotiation = 42,
        Power = 43,
        Game = 44,
        OurRequirement = 45,
        TheirRequirement = 46,
        CulturePlan = 47,
        Preparation = 48,
        EventTimeline = 49,
        PostEventAction = 50,
        OutcomeAndLearning = 51,
        BackgroundToTheNegotiation = 1112,
        MeetingManagement = 1113,
        ScopetoNegotiateandObjectives = 1114,
        NegotiationPlan = 1115,
}
